/**
 * OsterdOps — Comprehensive Demo Mode Mock Fixtures
 * Powers the interactive sandbox environment with hyper-realistic enterprise data:
 * - 7 Connected Frontier & Open Source Model Providers
 * - Active Gateway API Keys with rate limits & SHA-256 hashes
 * - Real-time Ingestion Requests Stream with token splits & cache status
 * - FinOps Budgets & Runaway Loop Circuit Breaker policies
 * - Enterprise Security Integrations (Slack, Datadog, PagerDuty, Webhook)
 */

import type { ProviderConnection } from "@/types";

export const DEMO_ORG_ID = "org_osterdops_demo_mesh";

export const DEMO_PROVIDER_CONNECTIONS: ProviderConnection[] = [
  {
    id: "conn_demo_openai",
    organizationId: DEMO_ORG_ID,
    provider: "openai",
    name: "OpenAI Production Mesh",
    displayName: "OpenAI Enterprise Tier-5 (Direct)",
    status: "active",
    encryptedKey: "",
    keyIv: "",
    keyTag: "",
    maskedKey: "sk-proj-••••••••••••9f42",
    models: ["gpt-4o", "gpt-4o-mini", "o3-mini", "o1-preview", "text-embedding-3-large"],
    defaultModel: "gpt-4o",
    maxSpendCap: 5000,
    fallbackModel: "claude-3-5-sonnet",
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    lastValidatedAt: new Date(Date.now() - 120000).toISOString(),
    lastUsedAt: new Date(Date.now() - 4000).toISOString(),
  },
  {
    id: "conn_demo_anthropic",
    organizationId: DEMO_ORG_ID,
    provider: "anthropic",
    name: "Anthropic Claude Production",
    displayName: "Anthropic Tier-4 Commercial Edge",
    status: "active",
    encryptedKey: "",
    keyIv: "",
    keyTag: "",
    maskedKey: "sk-ant-api03-••••••••••••7a11",
    models: ["claude-3-5-sonnet", "claude-3-5-haiku", "claude-3-opus"],
    defaultModel: "claude-3-5-sonnet",
    maxSpendCap: 4000,
    fallbackModel: "gemini-2.0-flash",
    createdAt: new Date(Date.now() - 40 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    lastValidatedAt: new Date(Date.now() - 180000).toISOString(),
    lastUsedAt: new Date(Date.now() - 14000).toISOString(),
  },
  {
    id: "conn_demo_gemini",
    organizationId: DEMO_ORG_ID,
    provider: "gemini",
    name: "Google Gemini Ultra-Low Latency",
    displayName: "Google Vertex & AI Studio (Sub-150ms)",
    status: "active",
    encryptedKey: "",
    keyIv: "",
    keyTag: "",
    maskedKey: "AIzaSy••••••••••••08b2",
    models: ["gemini-2.0-flash", "gemini-2.5-pro", "gemini-2.0-flash-thinking"],
    defaultModel: "gemini-2.0-flash",
    maxSpendCap: 2500,
    fallbackModel: "deepseek-chat",
    createdAt: new Date(Date.now() - 35 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 3600000).toISOString(),
    lastValidatedAt: new Date(Date.now() - 60000).toISOString(),
    lastUsedAt: new Date(Date.now() - 2000).toISOString(),
  },
  {
    id: "conn_demo_deepseek",
    organizationId: DEMO_ORG_ID,
    provider: "deepseek",
    name: "DeepSeek Frontier Reasoning",
    displayName: "DeepSeek API V3 & R1 Reasoning Engine",
    status: "active",
    encryptedKey: "",
    keyIv: "",
    keyTag: "",
    maskedKey: "sk-••••••••••••43c9",
    models: ["deepseek-chat", "deepseek-reasoner"],
    defaultModel: "deepseek-chat",
    maxSpendCap: 1500,
    fallbackModel: "gpt-4o-mini",
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    lastValidatedAt: new Date(Date.now() - 300000).toISOString(),
    lastUsedAt: new Date(Date.now() - 28000).toISOString(),
  },
  {
    id: "conn_demo_azure",
    organizationId: DEMO_ORG_ID,
    provider: "azure",
    name: "Microsoft Azure OpenAI EastUS",
    displayName: "Azure Private Gateway Endpoint (VPC)",
    status: "active",
    encryptedKey: "",
    keyIv: "",
    keyTag: "",
    maskedKey: "az-eastus-••••••••••••c18a",
    customBaseUrl: "https://osterdops-prod.openai.azure.com",
    models: ["gpt-4o", "gpt-4-turbo", "gpt-35-turbo"],
    defaultModel: "gpt-4o",
    maxSpendCap: 6000,
    createdAt: new Date(Date.now() - 50 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 3600000).toISOString(),
    lastValidatedAt: new Date(Date.now() - 400000).toISOString(),
    lastUsedAt: new Date(Date.now() - 55000).toISOString(),
  },
  {
    id: "conn_demo_groq",
    organizationId: DEMO_ORG_ID,
    provider: "groq",
    name: "Groq LPU Sub-100ms Accelerator",
    displayName: "Groq Ultra-Fast LPUs (850 tokens/sec)",
    status: "active",
    encryptedKey: "",
    keyIv: "",
    keyTag: "",
    maskedKey: "gsk_••••••••••••e421",
    models: ["llama-3.3-70b-versatile", "mixtral-8x7b-32768", "deepseek-r1-distill-llama-70b"],
    defaultModel: "llama-3.3-70b-versatile",
    maxSpendCap: 1000,
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    lastValidatedAt: new Date(Date.now() - 150000).toISOString(),
    lastUsedAt: new Date(Date.now() - 12000).toISOString(),
  },
  {
    id: "conn_demo_mistral",
    organizationId: DEMO_ORG_ID,
    provider: "mistral",
    name: "Mistral AI Europe Gateway",
    displayName: "Mistral AI Sovereign EU Data Residency",
    status: "active",
    encryptedKey: "",
    keyIv: "",
    keyTag: "",
    maskedKey: "mis_••••••••••••72fa",
    models: ["mistral-large-latest", "codestral-latest", "pixtral-large"],
    defaultModel: "mistral-large-latest",
    maxSpendCap: 1200,
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 3600000).toISOString(),
    lastValidatedAt: new Date(Date.now() - 220000).toISOString(),
    lastUsedAt: new Date(Date.now() - 95000).toISOString(),
  },
];

export const DEMO_API_KEYS = [
  {
    id: "key_demo_01",
    name: "Primary Production Gateway Ingestion",
    keyPrefix: "ost_live_prod_99f4••••",
    projectName: "Production Ingestion",
    environment: "production",
    lastUsed: "2 mins ago",
    createdAt: "12 days ago",
    status: "ACTIVE" as const,
  },
  {
    id: "key_demo_02",
    name: "Core Platform Dynamic Router",
    keyPrefix: "ost_live_stage_44a1••••",
    projectName: "Core Platform",
    environment: "staging",
    lastUsed: "14 mins ago",
    createdAt: "18 days ago",
    status: "ACTIVE" as const,
  },
  {
    id: "key_demo_03",
    name: "Automated Benchmark & Evals Pipeline",
    keyPrefix: "ost_live_eval_22c8••••",
    projectName: "R&D Experiments",
    environment: "evaluation",
    lastUsed: "1 hour ago",
    createdAt: "25 days ago",
    status: "ACTIVE" as const,
  },
  {
    id: "key_demo_04",
    name: "Autonomous Coding Agent Fleet",
    keyPrefix: "ost_live_agent_77d3••••",
    projectName: "AI Agents",
    environment: "production",
    lastUsed: "Just now",
    createdAt: "8 days ago",
    status: "ACTIVE" as const,
  },
  {
    id: "key_demo_05",
    name: "FinOps Chargeback & Billing Webhook",
    keyPrefix: "ost_live_finops_11e0••••",
    projectName: "Finance & Accounting",
    environment: "production",
    lastUsed: "3 hours ago",
    createdAt: "30 days ago",
    status: "ACTIVE" as const,
  },
];

export const DEMO_REQUEST_ITEMS = [
  {
    id: "req_live_01",
    timestamp: new Date(Date.now() - 4000).toISOString().replace("T", " ").slice(0, 19),
    model: "claude-3-5-sonnet",
    provider: "Anthropic",
    statusCode: 200,
    latencyMs: 420,
    tokens: 1800,
    costUsd: 0.00996,
    promptTokens: 1420,
    completionTokens: 380,
  },
  {
    id: "req_live_02",
    timestamp: new Date(Date.now() - 14000).toISOString().replace("T", " ").slice(0, 19),
    model: "gemini-2.0-flash",
    provider: "Google",
    statusCode: 200,
    latencyMs: 145,
    tokens: 4050,
    costUsd: 0.00062,
    promptTokens: 3200,
    completionTokens: 850,
  },
  {
    id: "req_live_03",
    timestamp: new Date(Date.now() - 28000).toISOString().replace("T", " ").slice(0, 19),
    model: "gpt-4o",
    provider: "OpenAI",
    statusCode: 200,
    latencyMs: 380,
    tokens: 1130,
    costUsd: 0.00463,
    promptTokens: 890,
    completionTokens: 240,
  },
  {
    id: "req_live_04",
    timestamp: new Date(Date.now() - 55000).toISOString().replace("T", " ").slice(0, 19),
    model: "deepseek-chat",
    provider: "DeepSeek",
    statusCode: 200,
    latencyMs: 290,
    tokens: 2720,
    costUsd: 0.00085,
    promptTokens: 2100,
    completionTokens: 620,
  },
  {
    id: "req_live_05",
    timestamp: new Date(Date.now() - 95000).toISOString().replace("T", " ").slice(0, 19),
    model: "claude-3-5-haiku",
    provider: "Anthropic",
    statusCode: 200,
    latencyMs: 180,
    tokens: 1170,
    costUsd: 0.00112,
    promptTokens: 980,
    completionTokens: 190,
  },
  {
    id: "req_live_06",
    timestamp: new Date(Date.now() - 145000).toISOString().replace("T", " ").slice(0, 19),
    model: "gemini-2.5-pro",
    provider: "Google",
    statusCode: 200,
    latencyMs: 610,
    tokens: 5700,
    costUsd: 0.0152,
    promptTokens: 4500,
    completionTokens: 1200,
  },
  {
    id: "req_live_07",
    timestamp: new Date(Date.now() - 210000).toISOString().replace("T", " ").slice(0, 19),
    model: "llama-3.3-70b-versatile",
    provider: "Groq",
    statusCode: 200,
    latencyMs: 88,
    tokens: 1540,
    costUsd: 0.00089,
    promptTokens: 1120,
    completionTokens: 420,
  },
  {
    id: "req_live_08",
    timestamp: new Date(Date.now() - 290000).toISOString().replace("T", " ").slice(0, 19),
    model: "gpt-4o",
    provider: "Azure OpenAI",
    statusCode: 429,
    latencyMs: 512,
    tokens: 850,
    costUsd: 0,
    promptTokens: 850,
    completionTokens: 0,
  },
  {
    id: "req_live_09",
    timestamp: new Date(Date.now() - 380000).toISOString().replace("T", " ").slice(0, 19),
    model: "o3-mini",
    provider: "OpenAI",
    statusCode: 200,
    latencyMs: 840,
    tokens: 2800,
    costUsd: 0.0078,
    promptTokens: 1900,
    completionTokens: 900,
  },
  {
    id: "req_live_10",
    timestamp: new Date(Date.now() - 490000).toISOString().replace("T", " ").slice(0, 19),
    model: "mistral-large-latest",
    provider: "Mistral",
    statusCode: 200,
    latencyMs: 340,
    tokens: 2100,
    costUsd: 0.0042,
    promptTokens: 1600,
    completionTokens: 500,
  },
];

export const DEMO_BUDGETS = [
  {
    id: "bgt_demo_01",
    name: "Enterprise Production Hard Cap (Monthly)",
    amount: 25000,
    spent: 17420.5,
    period: "MONTHLY",
    enforcement: "HARD",
    status: "ACTIVE",
    utilizationPercent: 69.7,
    department: "Engineering Infrastructure",
  },
  {
    id: "bgt_demo_02",
    name: "Core Platform GPT-4o Allocation",
    amount: 10000,
    spent: 6850.25,
    period: "MONTHLY",
    enforcement: "SOFT",
    status: "ACTIVE",
    utilizationPercent: 68.5,
    department: "Core Platform",
  },
  {
    id: "bgt_demo_03",
    name: "R&D Frontier Reasoning Models (DeepSeek & o3)",
    amount: 5000,
    spent: 2340.8,
    period: "MONTHLY",
    enforcement: "SOFT",
    status: "ACTIVE",
    utilizationPercent: 46.8,
    department: "AI Research",
  },
  {
    id: "bgt_demo_04",
    name: "Autonomous Agents Runaway Loop Breaker",
    amount: 2500,
    spent: 890.1,
    period: "MONTHLY",
    enforcement: "HARD",
    status: "ACTIVE",
    utilizationPercent: 35.6,
    department: "Applied AI",
  },
];
